apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "jenkins.connect.cd"
    external-dns.alpha.kubernetes.io/ttl: "10"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: master
  type: LoadBalancer
